fx_version 'cerulean'
game 'gta5'
version '0.0.1'
author 'Infinity'
description 'HUD | Player'
shared_script 'CLconfig.lua'
client_script 'client/*.lua'
ui_page 'html/ui.html'
file 'html/***/***/***/***'